### ISSUE TITLE
Link to UR Storybook is DEAD

### ISSUE THREAD

**Issue by DasGruene** [UniversalRobots/PolyScopeX_URCap_SDK#2]
The links to the UR storybook is broken inside the documentation.
https://docs.universal-robots.com/PolyScopeX_SDK_Documentation/build/PSX-SDK-v0.12/GettingStarted.html#my-first-urcap-guide
https://storybook.urrd.dk/?path=/docs/components-dropdown--docs
https://storybook.urrd.dk/?path=/docs/components-slider--docs

**Comment by EbbeFuglsang** [comment]
The links should be live now
